import { getGitHubClient, getGitHubConfig, setGitHubConfig } from './client'
import type { GitHubConfig } from '@/types/sync'
import { GitHubRepoError } from './errors'

const DEFAULT_REPO_NAME = 'mermaid-diagrams-backup'
const DEFAULT_BRANCH = 'main'

/**
 * 初始化或获取仓库
 */
export async function initializeRepo(
  owner: string,
  repoName: string = DEFAULT_REPO_NAME,
  token: string
): Promise<GitHubConfig> {
  const client = getGitHubClient()

  // 检查仓库是否存在
  let repoExists = false
  try {
    await client.repos.get({ owner, repo: repoName })
    repoExists = true
  } catch (error) {
    const err = error as { status?: number }
    if (err.status !== 404) {
      throw new GitHubRepoError('Failed to check repository', error as Error)
    }
  }

  // 创建仓库（如果不存在）
  if (!repoExists) {
    try {
      await client.repos.createForAuthenticatedUser({
        name: repoName,
        description: 'Mermaid diagrams backup - Auto-generated by Mermaid Editor',
        private: true,
        auto_init: true,
      })
      // 等待仓库初始化完成
      await new Promise((resolve) => setTimeout(resolve, 1000))
    } catch (error) {
      throw new GitHubRepoError('Failed to create repository', error as Error)
    }
  }

  // 初始化目录结构
  await initializeRepoStructure(owner, repoName)

  const config: GitHubConfig = {
    token,
    owner,
    repo: repoName,
    branch: DEFAULT_BRANCH,
  }

  setGitHubConfig(config)
  return config
}

/**
 * 初始化仓库目录结构
 */
async function initializeRepoStructure(owner: string, repo: string): Promise<void> {
  const client = getGitHubClient()

  // 检查 config.json 是否存在
  try {
    await client.repos.getContent({ owner, repo, path: 'config.json' })
    return // 已初始化
  } catch (error) {
    const err = error as { status?: number }
    if (err.status !== 404) throw error
  }

  // 创建初始配置文件
  const initialConfig = {
    version: '1.0.0',
    createdAt: new Date().toISOString(),
    lastSync: null,
  }

  await client.repos.createOrUpdateFileContents({
    owner,
    repo,
    path: 'config.json',
    message: 'Initialize Mermaid backup repository',
    content: btoa(JSON.stringify(initialConfig, null, 2)),
  })

  // 创建 README
  const readme = `# Mermaid Diagrams Backup

This repository is auto-generated by Mermaid Editor for cloud backup.

## Structure

\`\`\`
data/
├── projects.json           # Projects metadata
├── projects/
│   └── [project-id]/
│       ├── meta.json       # Project details
│       └── diagrams/
│           └── [id].mmd    # Diagram source
└── snapshots/
    └── [diagram-id]/
        └── [id].json       # Snapshot data
\`\`\`

**Do not manually edit these files.**
`

  await client.repos.createOrUpdateFileContents({
    owner,
    repo,
    path: 'README.md',
    message: 'Add README',
    content: btoa(readme),
  })
}

/**
 * 获取仓库信息
 */
export async function getRepoInfo(): Promise<{
  name: string
  private: boolean
  size: number
  updatedAt: string
}> {
  const client = getGitHubClient()
  const config = getGitHubConfig()

  const { data } = await client.repos.get({
    owner: config.owner,
    repo: config.repo,
  })

  return {
    name: data.name,
    private: data.private,
    size: data.size,
    updatedAt: data.updated_at,
  }
}
